### ISSUE TITLE
Repository Initialization

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1]
**Description:**
Setting up the skeleton of Inventory Management System 

**Task List:**
- [x] Run Create React-app and install Yarn
- [x] Add Dependencies 
- [x] Add MUI v5 and emotion packages 
- [x] Convert into a SciGateway plugin  
- [x] #19
- [x] Containerise App (#19)
- [x] Restructure the Repository 

**Useful links:**
- https://github.com/ral-facilities/scigateway/wiki/Creating-a-new-plugin-app

**Notes:**
- Look at Operation gateway implementation
- React 18 PR in Operation gateway
