### ISSUE TITLE
Upload attachments  dialog

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#1027]
#### Tasks:
- [x] Use **Uppy** with **AWS-S3** integration for the **upload dialog**.
- [x] Implement this dialog in the **common** components folder for reusability.
- [x] Make necessary **configuration changes** to connect with the object store API.
- [x] Provisionally create **hooks** to handle the removal of metadata:
  - When there is an **upload error**.
  - If the file is **removed mid-download**.
