### ISSUE TITLE
View Attachments

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1064]
#### Tasks:
- [ ] Create a **TableView** to display all attachments associated with a given `entity_id`.
- [ ] Use **Material React Table (MRT)** for the implementation.
- [ ] Ensure the table columns include:
  - **Filename**
  - **Title**
  - **Description**
  - **Created Time**
  - **Modified Time**
- [ ] Implement **pagination** and ensure it matches the pagination style used in other tables within the Inventory Management System (IMS).
- [ ] Generate mock data (chatgpt)
