### ISSUE TITLE
Single download for Attachments

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1066]
#### Tasks:
- [ ] Add an **Actions** column to the `Attachments` table.
- [ ] Add a **Download** `MenuItem` with the Material UI **Download** icon.
- [ ] Implement the logic to **fetch and download an attachment** when the "Download" menu item is clicked.
- [ ] Ensure the **menu closes** after the download action is triggered.
- [ ] Implement a **GET** request to fetch the attachment for download.
