### ISSUE TITLE
Multiple download for Attachments

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1067]
#### Tasks:
- [ ] Add **Checkboxes** to each row in the `Attachments` table to allow selection of multiple attachments.
- [ ] Add a **Download** button in the header of the table.
- [ ] The **Download** button should display the number of selected attachments (e.g., "4 Attachments download").
- [ ] Implement the logic to **download multiple attachments** when the download button is clicked.

**Comment by joshuadkitenge** [comment]
#1079
