### ISSUE TITLE
Edit Attachment metadata

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1068]
#### Tasks:
- [ ] Create a **dialog** for editing the metadata of attachments (e.g., title, description).
- [ ] Add an **Edit** `MenuItem` to the **Attachments** table for each attachment.
- [ ] Implement a **PATCH** endpoint to update attachment metadata in the backend.

#### notes:
might be able to reuse this dialog #1075
