### ISSUE TITLE
Delete Attachment

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1069]
#### Tasks:
- [ ] Create a **Delete** confirmation dialog for attachments.
- [ ] Implement a **DELETE** endpoint to remove attachments from the backend.
- [ ] Add a **Delete** `MenuItem` to the **Attachments** table for each attachment in the tile action menu.

#### Notes:
- No bulk delete; this functionality will be addressed later in #183.
- This could be shared with #1074
