### ISSUE TITLE
Delete images

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#1074]
#### Tasks:
- [ ] Create a **Delete** confirmation dialog for images.
- [ ] Implement a **DELETE** endpoint to remove images from the backend.
- [ ] Add a **Delete** `MenuItem` to the **Images** for each image tileActionMenu.

#### Notes:
- No bulk delete this should be later with #183
- This could be shared with #1069
