### ISSUE TITLE
Edit images

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#1075]
#### Tasks:
- [ ] Create a **dialog** for editing the metadata of images (e.g., title, description). 
- [ ] Add an **Edit** `MenuItem` to the **Images** for each image in the tile action menu. 
- [ ] Implement a **PATCH** endpoint to update images metadata in the backend.

#### notes:
might be able to reuse this dialog #1068
