### ISSUE TITLE
Single download for Images

### ISSUE THREAD

**Issue by joshdimanteto** [ral-facilities/inventory-management-system#1078]
#### Tasks:
- [ ] Add an **Horizon Icon Button**  to the `Images` thumbnail tile.
- [ ] Add a **Download** `MenuItem` with the Material UI **Download** icon.
- [ ] Implement the logic to **fetch and download an image** when the "Download" menu item is clicked.
- [ ] Ensure the **menu closes** after the download action is triggered.
- [ ] Implement a **GET** request to fetch the image for download.
