### ISSUE TITLE
Add Action Menu (e.g., download, delete) from the thumbnail view in the gallery.

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#1083]
#### Tasks:
- [ ] Use **React PhotoSwipe** UI elements to add the **Action Menu** to the gallery view.
  - [ ] Follow the [React PhotoSwipe custom UI elements documentation](https://github.com/dromru/react-photoswipe-gallery?tab=readme-ov-file#custom-ui-elements) to implement the custom actions.
- [ ] Include the following actions in the menu:
  - **Download**
  - **Delete**
  - **Edit**
  - **info**
- [ ] Test the actions to verify they work correctly within the **Gallery View**.
